version: '2'

services:

  mongodb:
    image: mongo
    hostname: mongodb
    domainname: critical-links.com
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/mongodb/:/var/lib/mongodb      
    env_file:
      - ./common.env
